export const TYPES = {
  App: Symbol.for('App'),
  DatabaseService: Symbol.for('DatabaseService'),
  ConfigService: Symbol.for('ConfigService'),
  LoggerService: Symbol.for('LoggerService'),
  BrokerService: Symbol.for('BrokerService'),
  BaseSchema: Symbol.for('BaseSchema'),
  ClientRepository: Symbol.for('ClientRepository'),
  ClientService: Symbol.for('ClientService'),
  ClientSchema: Symbol.for('ClientSchema'),
  ObjectRepository: Symbol.for('ObjectRepository'),
  ObjectService: Symbol.for('ObjectService'),
  ObjectSchema: Symbol.for('ObjectSchema'),
  ProductRepository: Symbol.for('ProductRepository'),
  ProductService: Symbol.for('ProductService'),
  ProductSchema: Symbol.for('ProductSchema'),
  ClientContractRepository: Symbol.for('ClientContractRepository'),
  ClientContractService: Symbol.for('ClientContractService'),
  ClientContractSchema: Symbol.for('ClientContractSchema'),
  AgencyRepository: Symbol.for('AgencyRepository'),
  AgencyService: Symbol.for('AgencyService'),
  AgencySchema: Symbol.for('AgencySchema'),
  AgencyContractRepository: Symbol.for('AgencyContractRepository'),
  AgencyContractService: Symbol.for('AgencyContractService'),
  AgencyContractSchema: Symbol.for('AgencyContractSchema'),
  RealEstateAgentRepository: Symbol.for('RealEstateAgentRepository'),
  RealEstateAgentService: Symbol.for('RealEstateAgentService'),
  RealEstateAgentSchema: Symbol.for('RealEstateAgentSchema'),
  UserRepository: Symbol.for('UserRepository'),
  UserService: Symbol.for('UserService'),
  UserSchema: Symbol.for('UserSchema'),
  BankRepository: Symbol.for('BankRepository'),
  BankService: Symbol.for('BankService'),
  BankSchema: Symbol.for('BankSchema'),
  ScheduledPaymentRepository: Symbol.for('ScheduledPaymentRepository'),
  ScheduledPaymentService: Symbol.for('ScheduledPaymentService'),
  ScheduledPaymentSchema: Symbol.for('ScheduledPaymentSchema'),
  ActualPaymentRepository: Symbol.for('ActualPaymentRepository'),
  ActualPaymentService: Symbol.for('ActualPaymentService'),
  ActualPaymentSchema: Symbol.for('ActualPaymentSchema'),
  EntityRepository: Symbol.for('EntityRepository'),
  EntityService: Symbol.for('EntityService'),
  EntitySchema: Symbol.for('EntitySchema'),
  EscrowAccountHistoryRepository: Symbol.for('EscrowAccountHistoryRepository'),
  EscrowAccountHistoryService: Symbol.for('EscrowAccountHistoryService'),
  EscrowAccountHistorySchema: Symbol.for('EscrowAccountHistorySchema'),
  RealEstateAgencyActRepository: Symbol.for('RealEstateAgencyActRepository'),
  RealEstateAgencyActService: Symbol.for('RealEstateAgencyActService'),
  RealEstateAgencyActSchema: Symbol.for('RealEstateAgencyActSchema'),
  SubsidyRepository: Symbol.for('SubsidyRepository'),
  SubsidyService: Symbol.for('SubsidyService'),
  SubsidySchema: Symbol.for('SubsidySchema'),
  AssignmentRepository: Symbol.for('AssignmentRepository'),
  AssignmentService: Symbol.for('AssignmentService'),
  AssignmentSchema: Symbol.for('AssignmentSchema'),
  RealEstateAgencyActCandidateRepository: Symbol.for(
    'RealEstateAgencyActCandidateRepository',
  ),
  RealEstateAgencyActCandidateService: Symbol.for(
    'RealEstateAgencyActCandidateService',
  ),
  RealEstateAgencyActCandidateSchema: Symbol.for(
    'RealEstateAgencyActCandidateSchema',
  ),
  TransferActRepository: Symbol.for('TransferActRepository'),
  TransferActService: Symbol.for('TransferActService'),
  TransferActSchema: Symbol.for('TransferActSchema'),
  RepresentativeRepository: Symbol.for('RepresentativeRepository'),
  RepresentativeService: Symbol.for('RepresentativeService'),
  RepresentativeSchema: Symbol.for('RepresentativeSchema'),
} as const;
