version: '3.9'

services:
  sales-client:
    container_name: sales-client
    build:
      context: ./packages/sales-client
    restart: unless-stopped
    networks:
      - sales-network

  sales-gateway:
    container_name: sales-gateway
    build:
      context: ./packages/sales-gateway
    volumes:
      - /var/log/sales:/var/log/sales
    depends_on:
      - sales-main
      - sales-common
      - sales-pricing
    restart: unless-stopped
    networks:
      - sales-network

  sales-main:
    container_name: sales-main
    build:
      context: ./packages/sales-main
    volumes:
      - /var/log/sales:/var/log/sales
    restart: unless-stopped
    networks:
      - sales-network

  sales-common:
    container_name: sales-common
    build:
      context: ./packages/sales-common
    volumes:
      - /var/log/sales:/var/log/sales
    restart: unless-stopped
    networks:
      - sales-network

  sales-pricing:
    container_name: sales-pricing
    build:
      context: ./packages/sales-pricing
    volumes:
      - /var/log/sales:/var/log/sales
    restart: unless-stopped
    networks:
      - sales-network

  sales-guard:
    container_name: sales-guard
    build:
      context: ./packages/sales-guard
    volumes:
      - /var/log/sales:/var/log/sales
    restart: unless-stopped
    networks:
      - sales-network

  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=***
      - VALIDATION=http
    volumes:
      - /swag/:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - sales-network
  
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - sales-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail.config.yml:/etc/promtail/config.yml
      - /var/log/sales:/var/log
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - sales-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=***
      - GF_SECURITY_ADMIN_PASSWORD=***
      - GF_SERVER_DOMAIN=***
      - GF_SERVER_ROOT_URL=***
      - GF_SERVER_ENFORCE_DOMAIN=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - sales-network

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
    networks:
      - sales-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.config.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - sales-network
      
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - sales-network

volumes:
  grafana_data:

networks:
  sales-network:
    driver: bridge
