version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: i5NJSiz3KKGRy2N^
      MYSQL_DATABASE: sales
      MYSQL_USER: sales_api
      MYSQL_PASSWORD: i5NJSiz3KKGRy2N^
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - sales-network

networks:
  sales-network:
    driver: bridge
