server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sales
    static_configs:
      - targets:
          - localhost
        labels:
          job: sales
          __path__: /var/log/sales-*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            service: service
            message: message
            meta: meta
