/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n\tquery GetAgenciesInAgencyContractPicker($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t}\n": types.GetAgenciesInAgencyContractPickerDocument,
    "\n\tquery GetAgencyContractsInAgencyContractPicker($input: GetAgencyContractsInput!) {\n\t\tgetAgencyContracts(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t}\n": types.GetAgencyContractsInAgencyContractPickerDocument,
    "\n\tquery GetAgencyContractSignatoriesInAgencyContractSignatoryPicker($input: GetAgencyContractSignatoriesInput!) {\n\t\tgetAgencyContractSignatories(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t\temail\n\t\t\tphone\n\t\t\ttitle\n\t\t\tbased_on\n\t\t}\n\t}\n": types.GetAgencyContractSignatoriesInAgencyContractSignatoryPickerDocument,
    "\n\tquery GetAgenciesInAgencyPicker($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n": types.GetAgenciesInAgencyPickerDocument,
    "\n\tquery GetBanksInBankPicker {\n\t\tgetBanks {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n": types.GetBanksInBankPickerDocument,
    "\n\tquery GetClientsInClientPicker($input: GetClientsInput!) {\n\t\tgetClients(input: $input) {\n\t\t\tclients {\n\t\t\t\tclient_properties {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientsInClientPickerDocument,
    "\n\tquery GetEntitiesInEntityPicker {\n\t\tgetEntities{\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobjects {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n": types.GetEntitiesInEntityPickerDocument,
    "\n\tmutation CreateActualPaymentInNewActualPayment($input: CreateActualPaymentInput!) {\n\t\tcreateActualPayment(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateActualPaymentInNewActualPaymentDocument,
    "\n\tmutation CreateAgencyContractSignatoryInNewAgencyContractSignatory($input: CreateAgencyContractSignatoryInput!) {\n\t\tcreateAgencyContractSignatory(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t\temail\n\t\t\tbased_on\n\t\t\tphone\n\t\t\ttitle\n\t\t}\n\t}\t\n": types.CreateAgencyContractSignatoryInNewAgencyContractSignatoryDocument,
    "\n\tmutation CreateScheduledPaymentInNewPaymentSchedule($input: CreateScheduledPaymentInput!) {\n\t\tcreateScheduledPayment(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateScheduledPaymentInNewPaymentScheduleDocument,
    "\n\tquery GetObjectsInObjectPicker {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n": types.GetObjectsInObjectPickerDocument,
    "\n\tquery GetPricingProductInProductInfo($input: GetPricingProductInput!) {\n\t\tgetPricingProduct(input: $input) {\n\t\t\tobject {\n\t\t\t\tname\n\t\t\t}\n\t\t\tcategory {\n\t\t\t\tname\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tarea\n\t\t\t\tprice\n\t\t\t\tone_gt_id\n\t\t\t}\n\t\t\tproduct_type {\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n": types.GetPricingProductInProductInfoDocument,
    "\n\tquery GetObjectsInProductPicker {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t\tcommon_db_objects_id\n\t\t}\n\t}\n": types.GetObjectsInProductPickerDocument,
    "\n\tquery GetPricingProductsInProductPicker($input: GetPricingProductsInput!) {\n\t\tgetPricingProducts(input: $input) {\n\t\t\tproducts {\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tarea\n\t\t\t\t\tprice\n\t\t\t\t}\n\t\t\t\tcategory {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetPricingProductsInProductPickerDocument,
    "\n\tmutation CreateProductInProductPicker($input: CreateProductInput!) {\n\t\tcreateProduct(input: $input) {\n\t\t\tproduct {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tpricing_products_id\n\t\t\t\tproduct_category\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t}\n\t}\n": types.CreateProductInProductPickerDocument,
    "\n\tquery GetRealEstateAgentsInRealEstateAgentPicker($input: GetRealEstateAgentsInput) {\n\t\tgetRealEstateAgents(input: $input) {\n\t\t\treal_estate_agents {\n\t\t\t\treal_estate_agent {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetRealEstateAgentsInRealEstateAgentPickerDocument,
    "\n\tquery GetClientContractsByIdsInRightPanel($input: GetClientContractsByIdsInput!) {\n\t\tgetClientContractsByIds(input: $input) {\n\t\t\tclient_contracts {\n\t\t\t\tclient_contract_properties {\n\t\t\t\t\tid\n\t\t\t\t\tdate\n\t\t\t\t\tnumber\n\t\t\t\t\tprice\n\t\t\t\t\tclient_contract_type\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tproduct {\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tproduct_category\n\t\t\t\t\t}\n\t\t\t\t\tobject {\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientContractsByIdsInRightPanelDocument,
    "\n\tquery GetUsersInUserPicker {\n\t\tgetUsers {\n\t\t\tid\n\t\t\tfull_name\n\t\t}\n\t}\n": types.GetUsersInUserPickerDocument,
    "\n\tquery GetAgenciesInAgencies($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n": types.GetAgenciesInAgenciesDocument,
    "\n\tquery GetAgencyAndAgencyContractsInAgency(\n\t\t$agencyInput: GetAgencyInput!\n\t\t$agencyContractsInput:GetAgencyContractsInput!\n\t) {\n\t\tgetAgency(input: $agencyInput) {\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tinn\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t\tgetAgencyContracts(input: $agencyContractsInput) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tcommon_db_objects_id\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n": types.GetAgencyAndAgencyContractsInAgencyDocument,
    "\n\tquery GetCommonContractorInAgency($input: GetCommonContractorInput!) {\n\t\tgetCommonContractor(input: $input) {\n\t\t\tcontractor {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tshort_name\n\t\t\t\tinn\n\t\t\t\tkpp\n\t\t\t\togrn\n\t\t\t\tlegal_address\n\t\t\t\tactual_address\n\t\t\t\tcontacts\n\t\t\t\treconciliation_link\n\t\t\t\tis_active\n\t\t\t\tpropogated_at\n\t\t\t\tphone\n\t\t\t}\n\t\t\taccounts {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tbank {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcity\n\t\t\t\t\tbik\n\t\t\t\t\tcorrespondent_number\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetCommonContractorInAgencyDocument,
    "\n\tquery GetObjectsInClientContracts {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t\tcommon_db_objects_id\n\t\t}\n\t}\n": types.GetObjectsInClientContractsDocument,
    "\n\tquery GetClientContractsInClientContracts($input: GetClientContractsInput!) {\n\t\tgetClientContracts(input: $input) {\n\t\t\tclient_contracts {\n\t\t\t\tclient_contract_properties {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tprice\n\t\t\t\t\tdate\n\t\t\t\t\tclient_contract_type\n\t\t\t\t}\n\t\t\t\tclients {\n\t\t\t\t\tclient {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfull_name\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tproduct {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tproduct_category\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n": types.GetClientContractsInClientContractsDocument,
    "\n\tquery GetClientEntityInClientEntity($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_entity_properties {\n\t\t\t\tkpp\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientEntityInClientEntityDocument,
    "\n\tmutation CreateClientEntityInClientEntity($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateClientEntityInClientEntityDocument,
    "\n\tmutation UpdateClientEntityInClientEntity($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n": types.UpdateClientEntityInClientEntityDocument,
    "\n\tquery GetClientIndividualMinorInClientIndividualMinor($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_individual_minor_properties {\n\t\t\t\tdob\n\t\t\t\tsnils\n\t\t\t\tbirth_certificate\n\t\t\t\tclient_passport {\n\t\t\t\t\tnumber\n\t\t\t\t\tissued\n\t\t\t\t\tcode\n\t\t\t\t\tplace_of_birth\n\t\t\t\t\tregistration_address\n\t\t\t\t}\n\t\t\t\trepresentatives {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientIndividualMinorInClientIndividualMinorDocument,
    "\n\tmutation CreateClientIndividualMinorInClientIndividualMinor($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateClientIndividualMinorInClientIndividualMinorDocument,
    "\n\tmutation UpdateClientIndividualMinorInClientIndividualMinor($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n": types.UpdateClientIndividualMinorInClientIndividualMinorDocument,
    "\n\tquery GetClientIndividualInClientIndividual($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_individual_properties {\n\t\t\t\tdob\n\t\t\t\tsnils\n\t\t\t\tclient_passport {\n\t\t\t\t\tnumber\n\t\t\t\t\tissued\n\t\t\t\t\tcode\n\t\t\t\t\tplace_of_birth\n\t\t\t\t\tregistration_address\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientIndividualInClientIndividualDocument,
    "\n\tmutation CreateClientIndividualInClientIndividual($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateClientIndividualInClientIndividualDocument,
    "\n\tmutation UpdateClientIndividualInClientIndividual($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n": types.UpdateClientIndividualInClientIndividualDocument,
    "\n\tquery GetClientsInClients($input: GetClientsInput!) {\n\t\tgetClients(input: $input) {\n\t\t\tclients {\n\t\t\t\tclient_properties {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n": types.GetClientsInClientsDocument,
    "\n\tquery GetClientContractInDDUClientContract($input: GetClientContractInput!) {\n\t\tgetClientContract(input: $input) {\n\t\t\tagency_contracts {\n\t\t\t\tagency_contract {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tdate\n\t\t\t\t\tagency_contract_type\n\t\t\t\t}\n\t\t\t\tagency {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcommon_db_contractors_id\n\t\t\t\t}\n\t\t\t}\n\t\t\tbank {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tclient_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tregistration_date\n\t\t\t\tprice\n\t\t\t\tclient_contract_type\n\t\t\t}\n\t\t\tclients {\n\t\t\t\tclient {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t\tis_main\n\t\t\t\tshare\n\t\t\t}\n\t\t\tddu_client_contract_properties {\n\t\t\t\tid\n\t\t\t\tis_escrow_discount\n\t\t\t\tescrow_account_opening_date\n\t\t\t\tescrow_period\n\t\t\t\tescrow_account_number\n\t\t\t\tddu_link\n\t\t\t\treturn_account\n\t\t\t}\n\t\t\tmanager {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tcommon_db_objects_id\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tpricing_products_id\n\t\t\t\t\tnumber\n\t\t\t\t\tproduct_category\n\t\t\t\t}\n\t\t\t}\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientContractInDduClientContractDocument,
    "\n\tmutation CreateClientContractInDDUClientContract($input: CreateClientContractInput!) {\n\t\tcreateClientContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateClientContractInDduClientContractDocument,
    "\n\tmutation UpdateClientContractInDDUClientContract($input: UpdateClientContractInput!) {\n\t\tupdateClientContract(input: $input) {\n\t\t\tid\n\t\t\tnumber\n\t\t}\n\t}\n": types.UpdateClientContractInDduClientContractDocument,
    "\n\tquery GetClientContractInDKPClientContract($input: GetClientContractInput!) {\n\t\tgetClientContract(input: $input) {\n\t\t\tagency_contracts {\n\t\t\t\tagency_contract {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tdate\n\t\t\t\t\tagency_contract_type\n\t\t\t\t}\n\t\t\t\tagency {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcommon_db_contractors_id\n\t\t\t\t}\n\t\t\t}\n\t\t\tbank {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tclient_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tregistration_date\n\t\t\t\tprice\n\t\t\t\tclient_contract_type\n\t\t\t}\n\t\t\tclients {\n\t\t\t\tclient {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t\tis_main\n\t\t\t\tshare\n\t\t\t}\n\t\t\tmanager {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tcommon_db_objects_id\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tpricing_products_id\n\t\t\t\t\tnumber\n\t\t\t\t\tproduct_category\n\t\t\t\t}\n\t\t\t}\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n": types.GetClientContractInDkpClientContractDocument,
    "\n\tmutation CreateClientContractInDKPClientContract($input: CreateClientContractInput!) {\n\t\tcreateClientContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateClientContractInDkpClientContractDocument,
    "\n\tmutation UpdateClientContractInDKPClientContract($input: UpdateClientContractInput!) {\n\t\tupdateClientContract(input: $input) {\n\t\t\tid\n\t\t\tnumber\n\t\t}\n\t}\n": types.UpdateClientContractInDkpClientContractDocument,
    "\n  query GetObjectsInMIPAgencyContract {\n\t\tgetObjects {\n      id\n      name\n\t\t}\n\t}\n": types.GetObjectsInMipAgencyContractDocument,
    "\n\tquery GetAgencyContractInMIPAgencyContract($input: GetAgencyContractInput!) {\n\t\tgetAgencyContract(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tagency_contract_signatory {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\ttitle\n\t\t\t\tbased_on\n\t\t\t}\n\t\t\tmip_agency_contract_properties {\n\t\t\t\tagency_contract_commission {\n\t\t\t\t\tpercent\n\t\t\t\t\tthreshold\n\t\t\t\t\tmax_days\n\t\t\t\t}\n\t\t\t}\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tresponsible_user {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n": types.GetAgencyContractInMipAgencyContractDocument,
    "\n  mutation CreateAgencyContractInMIPAgencyContract($input: CreateAgencyContractInput!) {\n\t\tcreateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateAgencyContractInMipAgencyContractDocument,
    "\n  mutation UpdateAgencyContractInMIPAgencyContract($input: UpdateAgencyContractInput!) {\n\t\tupdateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.UpdateAgencyContractInMipAgencyContractDocument,
    "\n\tquery GetCommonContractorsInNewAgency($input: GetCommonContractorsInput!) {\n\t\tgetCommonContractors(input: $input) {\n\t\t\tcontractors {\n\t\t\t\tcontractor {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tshort_name\n\t\t\t\t\tinn\n\t\t\t\t\tkpp\n\t\t\t\t\togrn\n\t\t\t\t\tlegal_address\n\t\t\t\t\tactual_address\n\t\t\t\t\tcontacts\n\t\t\t\t\treconciliation_link\n\t\t\t\t\tis_active\n\t\t\t\t\tpropogated_at\n\t\t\t\t\tphone\n\t\t\t\t}\n\t\t\t\taccounts {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tbank {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcity\n\t\t\t\t\t\tbik\n\t\t\t\t\t\tcorrespondent_number\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n": types.GetCommonContractorsInNewAgencyDocument,
    "\n\tmutation CreateAgencyInNewAgency($input: CreateAgencyInput!) {\n\t\tcreateAgency(input: $input) {\n\t\t\tid\n\t\t}\n\t}\t\n": types.CreateAgencyInNewAgencyDocument,
    "\n\tquery GetScheduledPaymentsInPaymentSchedule($getScheduledPaymentsInput: GetScheduledPaymentsInput!, $getActualPaymentsInput: GetActualPaymentsInput!) {\n\t\tgetScheduledPayments(input: $getScheduledPaymentsInput) {\n\t\t\tscheduled_payments {\n\t\t\t\tid\n\t\t\t\tdate\n\t\t\t\tpayment\n\t\t\t\tscheduled_payment_type\n\t\t\t}\n\t\t}\n\t\tgetActualPayments(input: $getActualPaymentsInput) {\n\t\t\tactual_payments {\n\t\t\t\tid\n\t\t\t\tdate\n\t\t\t\tpayment\n\t\t\t}\n\t\t}\n\t}\n": types.GetScheduledPaymentsInPaymentScheduleDocument,
    "\n  query GetObjectsInNewAgencyContract {\n\t\tgetObjects {\n      id\n      name\n\t\t}\n\t}\n": types.GetObjectsInNewAgencyContractDocument,
    "\n\tquery GetAgencyContractInRealEstateAgencyContract($input: GetAgencyContractInput!) {\n\t\tgetAgencyContract(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tagency_contract_signatory {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\ttitle\n\t\t\t\tbased_on\n\t\t\t}\n\t\t\treal_estate_agency_contract_properties {\n\t\t\t\tagency_contract_commission {\n\t\t\t\t\tpercent\n\t\t\t\t\tthreshold\n\t\t\t\t\tmax_days\n\t\t\t\t}\n\t\t\t}\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tresponsible_user {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n": types.GetAgencyContractInRealEstateAgencyContractDocument,
    "\n  mutation CreateAgencyContractInNewAgencyContract($input: CreateAgencyContractInput!) {\n\t\tcreateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateAgencyContractInNewAgencyContractDocument,
    "\n  mutation UpdateAgencyContractInNewAgencyContract($input: UpdateAgencyContractInput!) {\n\t\tupdateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.UpdateAgencyContractInNewAgencyContractDocument,
    "\n\tquery GetRealEstateAgentInRealEstateAgent($input: GetRealEstateAgentInput!) {\n\t\tgetRealEstateAgent(input: $input) {\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tphone\n\t\t\t}\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tcommon_db_contractors_id\n\t\t\t\tname\n\t\t\t\tinn\n\t\t\t}\n\t\t}\n\t}\n": types.GetRealEstateAgentInRealEstateAgentDocument,
    "\n\tmutation CreateRealEstateAgentInNewRealEstateAgent($input: CreateRealEstateAgentInput!) {\n\t\tcreateRealEstateAgent(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n": types.CreateRealEstateAgentInNewRealEstateAgentDocument,
    "\n\tmutation UpdateRealEstateAgentInRealEstateAgent($input: UpdateRealEstateAgentInput!) {\n\t\tupdateRealEstateAgent(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t}\n\t}\n": types.UpdateRealEstateAgentInRealEstateAgentDocument,
    "\n\tquery GetRealEstateAgentsInRealEstateAgents($input: GetRealEstateAgentsInput!) {\n\t\tgetRealEstateAgents(input: $input) {\n\t\t\treal_estate_agents {\n\t\t\t\treal_estate_agent {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tphone\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n": types.GetRealEstateAgentsInRealEstateAgentsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgenciesInAgencyContractPicker($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgenciesInAgencyContractPicker($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgencyContractsInAgencyContractPicker($input: GetAgencyContractsInput!) {\n\t\tgetAgencyContracts(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgencyContractsInAgencyContractPicker($input: GetAgencyContractsInput!) {\n\t\tgetAgencyContracts(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgencyContractSignatoriesInAgencyContractSignatoryPicker($input: GetAgencyContractSignatoriesInput!) {\n\t\tgetAgencyContractSignatories(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t\temail\n\t\t\tphone\n\t\t\ttitle\n\t\t\tbased_on\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgencyContractSignatoriesInAgencyContractSignatoryPicker($input: GetAgencyContractSignatoriesInput!) {\n\t\tgetAgencyContractSignatories(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t\temail\n\t\t\tphone\n\t\t\ttitle\n\t\t\tbased_on\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgenciesInAgencyPicker($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgenciesInAgencyPicker($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetBanksInBankPicker {\n\t\tgetBanks {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetBanksInBankPicker {\n\t\tgetBanks {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientsInClientPicker($input: GetClientsInput!) {\n\t\tgetClients(input: $input) {\n\t\t\tclients {\n\t\t\t\tclient_properties {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientsInClientPicker($input: GetClientsInput!) {\n\t\tgetClients(input: $input) {\n\t\t\tclients {\n\t\t\t\tclient_properties {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetEntitiesInEntityPicker {\n\t\tgetEntities{\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobjects {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetEntitiesInEntityPicker {\n\t\tgetEntities{\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobjects {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateActualPaymentInNewActualPayment($input: CreateActualPaymentInput!) {\n\t\tcreateActualPayment(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateActualPaymentInNewActualPayment($input: CreateActualPaymentInput!) {\n\t\tcreateActualPayment(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateAgencyContractSignatoryInNewAgencyContractSignatory($input: CreateAgencyContractSignatoryInput!) {\n\t\tcreateAgencyContractSignatory(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t\temail\n\t\t\tbased_on\n\t\t\tphone\n\t\t\ttitle\n\t\t}\n\t}\t\n"): (typeof documents)["\n\tmutation CreateAgencyContractSignatoryInNewAgencyContractSignatory($input: CreateAgencyContractSignatoryInput!) {\n\t\tcreateAgencyContractSignatory(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t\temail\n\t\t\tbased_on\n\t\t\tphone\n\t\t\ttitle\n\t\t}\n\t}\t\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateScheduledPaymentInNewPaymentSchedule($input: CreateScheduledPaymentInput!) {\n\t\tcreateScheduledPayment(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateScheduledPaymentInNewPaymentSchedule($input: CreateScheduledPaymentInput!) {\n\t\tcreateScheduledPayment(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetObjectsInObjectPicker {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetObjectsInObjectPicker {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetPricingProductInProductInfo($input: GetPricingProductInput!) {\n\t\tgetPricingProduct(input: $input) {\n\t\t\tobject {\n\t\t\t\tname\n\t\t\t}\n\t\t\tcategory {\n\t\t\t\tname\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tarea\n\t\t\t\tprice\n\t\t\t\tone_gt_id\n\t\t\t}\n\t\t\tproduct_type {\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetPricingProductInProductInfo($input: GetPricingProductInput!) {\n\t\tgetPricingProduct(input: $input) {\n\t\t\tobject {\n\t\t\t\tname\n\t\t\t}\n\t\t\tcategory {\n\t\t\t\tname\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tarea\n\t\t\t\tprice\n\t\t\t\tone_gt_id\n\t\t\t}\n\t\t\tproduct_type {\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetObjectsInProductPicker {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t\tcommon_db_objects_id\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetObjectsInProductPicker {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t\tcommon_db_objects_id\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetPricingProductsInProductPicker($input: GetPricingProductsInput!) {\n\t\tgetPricingProducts(input: $input) {\n\t\t\tproducts {\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tarea\n\t\t\t\t\tprice\n\t\t\t\t}\n\t\t\t\tcategory {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetPricingProductsInProductPicker($input: GetPricingProductsInput!) {\n\t\tgetPricingProducts(input: $input) {\n\t\t\tproducts {\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tarea\n\t\t\t\t\tprice\n\t\t\t\t}\n\t\t\t\tcategory {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateProductInProductPicker($input: CreateProductInput!) {\n\t\tcreateProduct(input: $input) {\n\t\t\tproduct {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tpricing_products_id\n\t\t\t\tproduct_category\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateProductInProductPicker($input: CreateProductInput!) {\n\t\tcreateProduct(input: $input) {\n\t\t\tproduct {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tpricing_products_id\n\t\t\t\tproduct_category\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetRealEstateAgentsInRealEstateAgentPicker($input: GetRealEstateAgentsInput) {\n\t\tgetRealEstateAgents(input: $input) {\n\t\t\treal_estate_agents {\n\t\t\t\treal_estate_agent {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetRealEstateAgentsInRealEstateAgentPicker($input: GetRealEstateAgentsInput) {\n\t\tgetRealEstateAgents(input: $input) {\n\t\t\treal_estate_agents {\n\t\t\t\treal_estate_agent {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientContractsByIdsInRightPanel($input: GetClientContractsByIdsInput!) {\n\t\tgetClientContractsByIds(input: $input) {\n\t\t\tclient_contracts {\n\t\t\t\tclient_contract_properties {\n\t\t\t\t\tid\n\t\t\t\t\tdate\n\t\t\t\t\tnumber\n\t\t\t\t\tprice\n\t\t\t\t\tclient_contract_type\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tproduct {\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tproduct_category\n\t\t\t\t\t}\n\t\t\t\t\tobject {\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientContractsByIdsInRightPanel($input: GetClientContractsByIdsInput!) {\n\t\tgetClientContractsByIds(input: $input) {\n\t\t\tclient_contracts {\n\t\t\t\tclient_contract_properties {\n\t\t\t\t\tid\n\t\t\t\t\tdate\n\t\t\t\t\tnumber\n\t\t\t\t\tprice\n\t\t\t\t\tclient_contract_type\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tproduct {\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tproduct_category\n\t\t\t\t\t}\n\t\t\t\t\tobject {\n\t\t\t\t\t\tname\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetUsersInUserPicker {\n\t\tgetUsers {\n\t\t\tid\n\t\t\tfull_name\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetUsersInUserPicker {\n\t\tgetUsers {\n\t\t\tid\n\t\t\tfull_name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgenciesInAgencies($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgenciesInAgencies($input: GetAgenciesInput!) {\n\t\tgetAgencies(input: $input) {\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgencyAndAgencyContractsInAgency(\n\t\t$agencyInput: GetAgencyInput!\n\t\t$agencyContractsInput:GetAgencyContractsInput!\n\t) {\n\t\tgetAgency(input: $agencyInput) {\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tinn\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t\tgetAgencyContracts(input: $agencyContractsInput) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tcommon_db_objects_id\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgencyAndAgencyContractsInAgency(\n\t\t$agencyInput: GetAgencyInput!\n\t\t$agencyContractsInput:GetAgencyContractsInput!\n\t) {\n\t\tgetAgency(input: $agencyInput) {\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tinn\n\t\t\t\tcommon_db_contractors_id\n\t\t\t}\n\t\t}\n\t\tgetAgencyContracts(input: $agencyContractsInput) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tcommon_db_objects_id\n\t\t\t\tname\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetCommonContractorInAgency($input: GetCommonContractorInput!) {\n\t\tgetCommonContractor(input: $input) {\n\t\t\tcontractor {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tshort_name\n\t\t\t\tinn\n\t\t\t\tkpp\n\t\t\t\togrn\n\t\t\t\tlegal_address\n\t\t\t\tactual_address\n\t\t\t\tcontacts\n\t\t\t\treconciliation_link\n\t\t\t\tis_active\n\t\t\t\tpropogated_at\n\t\t\t\tphone\n\t\t\t}\n\t\t\taccounts {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tbank {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcity\n\t\t\t\t\tbik\n\t\t\t\t\tcorrespondent_number\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetCommonContractorInAgency($input: GetCommonContractorInput!) {\n\t\tgetCommonContractor(input: $input) {\n\t\t\tcontractor {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tshort_name\n\t\t\t\tinn\n\t\t\t\tkpp\n\t\t\t\togrn\n\t\t\t\tlegal_address\n\t\t\t\tactual_address\n\t\t\t\tcontacts\n\t\t\t\treconciliation_link\n\t\t\t\tis_active\n\t\t\t\tpropogated_at\n\t\t\t\tphone\n\t\t\t}\n\t\t\taccounts {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tbank {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcity\n\t\t\t\t\tbik\n\t\t\t\t\tcorrespondent_number\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetObjectsInClientContracts {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t\tcommon_db_objects_id\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetObjectsInClientContracts {\n\t\tgetObjects {\n\t\t\tid\n\t\t\tname\n\t\t\tcommon_db_objects_id\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientContractsInClientContracts($input: GetClientContractsInput!) {\n\t\tgetClientContracts(input: $input) {\n\t\t\tclient_contracts {\n\t\t\t\tclient_contract_properties {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tprice\n\t\t\t\t\tdate\n\t\t\t\t\tclient_contract_type\n\t\t\t\t}\n\t\t\t\tclients {\n\t\t\t\t\tclient {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfull_name\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tproduct {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tproduct_category\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientContractsInClientContracts($input: GetClientContractsInput!) {\n\t\tgetClientContracts(input: $input) {\n\t\t\tclient_contracts {\n\t\t\t\tclient_contract_properties {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tprice\n\t\t\t\t\tdate\n\t\t\t\t\tclient_contract_type\n\t\t\t\t}\n\t\t\t\tclients {\n\t\t\t\t\tclient {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tfull_name\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tproduct {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tnumber\n\t\t\t\t\t\tproduct_category\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientEntityInClientEntity($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_entity_properties {\n\t\t\t\tkpp\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientEntityInClientEntity($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_entity_properties {\n\t\t\t\tkpp\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateClientEntityInClientEntity($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateClientEntityInClientEntity($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateClientEntityInClientEntity($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation UpdateClientEntityInClientEntity($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientIndividualMinorInClientIndividualMinor($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_individual_minor_properties {\n\t\t\t\tdob\n\t\t\t\tsnils\n\t\t\t\tbirth_certificate\n\t\t\t\tclient_passport {\n\t\t\t\t\tnumber\n\t\t\t\t\tissued\n\t\t\t\t\tcode\n\t\t\t\t\tplace_of_birth\n\t\t\t\t\tregistration_address\n\t\t\t\t}\n\t\t\t\trepresentatives {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientIndividualMinorInClientIndividualMinor($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_individual_minor_properties {\n\t\t\t\tdob\n\t\t\t\tsnils\n\t\t\t\tbirth_certificate\n\t\t\t\tclient_passport {\n\t\t\t\t\tnumber\n\t\t\t\t\tissued\n\t\t\t\t\tcode\n\t\t\t\t\tplace_of_birth\n\t\t\t\t\tregistration_address\n\t\t\t\t}\n\t\t\t\trepresentatives {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateClientIndividualMinorInClientIndividualMinor($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateClientIndividualMinorInClientIndividualMinor($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateClientIndividualMinorInClientIndividualMinor($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation UpdateClientIndividualMinorInClientIndividualMinor($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientIndividualInClientIndividual($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_individual_properties {\n\t\t\t\tdob\n\t\t\t\tsnils\n\t\t\t\tclient_passport {\n\t\t\t\t\tnumber\n\t\t\t\t\tissued\n\t\t\t\t\tcode\n\t\t\t\t\tplace_of_birth\n\t\t\t\t\tregistration_address\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientIndividualInClientIndividual($input: GetClientInput!) {\n\t\tgetClient(input: $input) {\n\t\t\tclient_properties {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tinn\n\t\t\t\tphone\n\t\t\t\temail\n\t\t\t\taddress\n\t\t\t\tclient_category\n\t\t\t}\n\t\t\tclient_individual_properties {\n\t\t\t\tdob\n\t\t\t\tsnils\n\t\t\t\tclient_passport {\n\t\t\t\t\tnumber\n\t\t\t\t\tissued\n\t\t\t\t\tcode\n\t\t\t\t\tplace_of_birth\n\t\t\t\t\tregistration_address\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateClientIndividualInClientIndividual($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateClientIndividualInClientIndividual($input: CreateClientInput!) {\n\t\tcreateClient(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateClientIndividualInClientIndividual($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation UpdateClientIndividualInClientIndividual($input: UpdateClientInput!) {\n\t\tupdateClient(input: $input) {\n\t\t\tfull_name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientsInClients($input: GetClientsInput!) {\n\t\tgetClients(input: $input) {\n\t\t\tclients {\n\t\t\t\tclient_properties {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientsInClients($input: GetClientsInput!) {\n\t\tgetClients(input: $input) {\n\t\t\tclients {\n\t\t\t\tclient_properties {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientContractInDDUClientContract($input: GetClientContractInput!) {\n\t\tgetClientContract(input: $input) {\n\t\t\tagency_contracts {\n\t\t\t\tagency_contract {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tdate\n\t\t\t\t\tagency_contract_type\n\t\t\t\t}\n\t\t\t\tagency {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcommon_db_contractors_id\n\t\t\t\t}\n\t\t\t}\n\t\t\tbank {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tclient_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tregistration_date\n\t\t\t\tprice\n\t\t\t\tclient_contract_type\n\t\t\t}\n\t\t\tclients {\n\t\t\t\tclient {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t\tis_main\n\t\t\t\tshare\n\t\t\t}\n\t\t\tddu_client_contract_properties {\n\t\t\t\tid\n\t\t\t\tis_escrow_discount\n\t\t\t\tescrow_account_opening_date\n\t\t\t\tescrow_period\n\t\t\t\tescrow_account_number\n\t\t\t\tddu_link\n\t\t\t\treturn_account\n\t\t\t}\n\t\t\tmanager {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tcommon_db_objects_id\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tpricing_products_id\n\t\t\t\t\tnumber\n\t\t\t\t\tproduct_category\n\t\t\t\t}\n\t\t\t}\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientContractInDDUClientContract($input: GetClientContractInput!) {\n\t\tgetClientContract(input: $input) {\n\t\t\tagency_contracts {\n\t\t\t\tagency_contract {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tdate\n\t\t\t\t\tagency_contract_type\n\t\t\t\t}\n\t\t\t\tagency {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcommon_db_contractors_id\n\t\t\t\t}\n\t\t\t}\n\t\t\tbank {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tclient_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tregistration_date\n\t\t\t\tprice\n\t\t\t\tclient_contract_type\n\t\t\t}\n\t\t\tclients {\n\t\t\t\tclient {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t\tis_main\n\t\t\t\tshare\n\t\t\t}\n\t\t\tddu_client_contract_properties {\n\t\t\t\tid\n\t\t\t\tis_escrow_discount\n\t\t\t\tescrow_account_opening_date\n\t\t\t\tescrow_period\n\t\t\t\tescrow_account_number\n\t\t\t\tddu_link\n\t\t\t\treturn_account\n\t\t\t}\n\t\t\tmanager {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tcommon_db_objects_id\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tpricing_products_id\n\t\t\t\t\tnumber\n\t\t\t\t\tproduct_category\n\t\t\t\t}\n\t\t\t}\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateClientContractInDDUClientContract($input: CreateClientContractInput!) {\n\t\tcreateClientContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateClientContractInDDUClientContract($input: CreateClientContractInput!) {\n\t\tcreateClientContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateClientContractInDDUClientContract($input: UpdateClientContractInput!) {\n\t\tupdateClientContract(input: $input) {\n\t\t\tid\n\t\t\tnumber\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation UpdateClientContractInDDUClientContract($input: UpdateClientContractInput!) {\n\t\tupdateClientContract(input: $input) {\n\t\t\tid\n\t\t\tnumber\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetClientContractInDKPClientContract($input: GetClientContractInput!) {\n\t\tgetClientContract(input: $input) {\n\t\t\tagency_contracts {\n\t\t\t\tagency_contract {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tdate\n\t\t\t\t\tagency_contract_type\n\t\t\t\t}\n\t\t\t\tagency {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcommon_db_contractors_id\n\t\t\t\t}\n\t\t\t}\n\t\t\tbank {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tclient_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tregistration_date\n\t\t\t\tprice\n\t\t\t\tclient_contract_type\n\t\t\t}\n\t\t\tclients {\n\t\t\t\tclient {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t\tis_main\n\t\t\t\tshare\n\t\t\t}\n\t\t\tmanager {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tcommon_db_objects_id\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tpricing_products_id\n\t\t\t\t\tnumber\n\t\t\t\t\tproduct_category\n\t\t\t\t}\n\t\t\t}\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetClientContractInDKPClientContract($input: GetClientContractInput!) {\n\t\tgetClientContract(input: $input) {\n\t\t\tagency_contracts {\n\t\t\t\tagency_contract {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tdate\n\t\t\t\t\tagency_contract_type\n\t\t\t\t}\n\t\t\t\tagency {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tcommon_db_contractors_id\n\t\t\t\t}\n\t\t\t}\n\t\t\tbank {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tclient_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tregistration_date\n\t\t\t\tprice\n\t\t\t\tclient_contract_type\n\t\t\t}\n\t\t\tclients {\n\t\t\t\tclient {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tclient_category\n\t\t\t\t}\n\t\t\t\tis_main\n\t\t\t\tshare\n\t\t\t}\n\t\t\tmanager {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t\tcommon_db_objects_id\n\t\t\t}\n\t\t\tproduct {\n\t\t\t\tobject {\n\t\t\t\t\tid\n\t\t\t\t\tcommon_db_objects_id\n\t\t\t\t\tname\n\t\t\t\t}\n\t\t\t\tproduct {\n\t\t\t\t\tid\n\t\t\t\t\tpricing_products_id\n\t\t\t\t\tnumber\n\t\t\t\t\tproduct_category\n\t\t\t\t}\n\t\t\t}\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateClientContractInDKPClientContract($input: CreateClientContractInput!) {\n\t\tcreateClientContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateClientContractInDKPClientContract($input: CreateClientContractInput!) {\n\t\tcreateClientContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateClientContractInDKPClientContract($input: UpdateClientContractInput!) {\n\t\tupdateClientContract(input: $input) {\n\t\t\tid\n\t\t\tnumber\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation UpdateClientContractInDKPClientContract($input: UpdateClientContractInput!) {\n\t\tupdateClientContract(input: $input) {\n\t\t\tid\n\t\t\tnumber\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetObjectsInMIPAgencyContract {\n\t\tgetObjects {\n      id\n      name\n\t\t}\n\t}\n"): (typeof documents)["\n  query GetObjectsInMIPAgencyContract {\n\t\tgetObjects {\n      id\n      name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgencyContractInMIPAgencyContract($input: GetAgencyContractInput!) {\n\t\tgetAgencyContract(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tagency_contract_signatory {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\ttitle\n\t\t\t\tbased_on\n\t\t\t}\n\t\t\tmip_agency_contract_properties {\n\t\t\t\tagency_contract_commission {\n\t\t\t\t\tpercent\n\t\t\t\t\tthreshold\n\t\t\t\t\tmax_days\n\t\t\t\t}\n\t\t\t}\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tresponsible_user {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgencyContractInMIPAgencyContract($input: GetAgencyContractInput!) {\n\t\tgetAgencyContract(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tagency_contract_signatory {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\ttitle\n\t\t\t\tbased_on\n\t\t\t}\n\t\t\tmip_agency_contract_properties {\n\t\t\t\tagency_contract_commission {\n\t\t\t\t\tpercent\n\t\t\t\t\tthreshold\n\t\t\t\t\tmax_days\n\t\t\t\t}\n\t\t\t}\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tresponsible_user {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateAgencyContractInMIPAgencyContract($input: CreateAgencyContractInput!) {\n\t\tcreateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n  mutation CreateAgencyContractInMIPAgencyContract($input: CreateAgencyContractInput!) {\n\t\tcreateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateAgencyContractInMIPAgencyContract($input: UpdateAgencyContractInput!) {\n\t\tupdateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n  mutation UpdateAgencyContractInMIPAgencyContract($input: UpdateAgencyContractInput!) {\n\t\tupdateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetCommonContractorsInNewAgency($input: GetCommonContractorsInput!) {\n\t\tgetCommonContractors(input: $input) {\n\t\t\tcontractors {\n\t\t\t\tcontractor {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tshort_name\n\t\t\t\t\tinn\n\t\t\t\t\tkpp\n\t\t\t\t\togrn\n\t\t\t\t\tlegal_address\n\t\t\t\t\tactual_address\n\t\t\t\t\tcontacts\n\t\t\t\t\treconciliation_link\n\t\t\t\t\tis_active\n\t\t\t\t\tpropogated_at\n\t\t\t\t\tphone\n\t\t\t\t}\n\t\t\t\taccounts {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tbank {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcity\n\t\t\t\t\t\tbik\n\t\t\t\t\t\tcorrespondent_number\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetCommonContractorsInNewAgency($input: GetCommonContractorsInput!) {\n\t\tgetCommonContractors(input: $input) {\n\t\t\tcontractors {\n\t\t\t\tcontractor {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tshort_name\n\t\t\t\t\tinn\n\t\t\t\t\tkpp\n\t\t\t\t\togrn\n\t\t\t\t\tlegal_address\n\t\t\t\t\tactual_address\n\t\t\t\t\tcontacts\n\t\t\t\t\treconciliation_link\n\t\t\t\t\tis_active\n\t\t\t\t\tpropogated_at\n\t\t\t\t\tphone\n\t\t\t\t}\n\t\t\t\taccounts {\n\t\t\t\t\tid\n\t\t\t\t\tnumber\n\t\t\t\t\tbank {\n\t\t\t\t\t\tid\n\t\t\t\t\t\tname\n\t\t\t\t\t\tcity\n\t\t\t\t\t\tbik\n\t\t\t\t\t\tcorrespondent_number\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateAgencyInNewAgency($input: CreateAgencyInput!) {\n\t\tcreateAgency(input: $input) {\n\t\t\tid\n\t\t}\n\t}\t\n"): (typeof documents)["\n\tmutation CreateAgencyInNewAgency($input: CreateAgencyInput!) {\n\t\tcreateAgency(input: $input) {\n\t\t\tid\n\t\t}\n\t}\t\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetScheduledPaymentsInPaymentSchedule($getScheduledPaymentsInput: GetScheduledPaymentsInput!, $getActualPaymentsInput: GetActualPaymentsInput!) {\n\t\tgetScheduledPayments(input: $getScheduledPaymentsInput) {\n\t\t\tscheduled_payments {\n\t\t\t\tid\n\t\t\t\tdate\n\t\t\t\tpayment\n\t\t\t\tscheduled_payment_type\n\t\t\t}\n\t\t}\n\t\tgetActualPayments(input: $getActualPaymentsInput) {\n\t\t\tactual_payments {\n\t\t\t\tid\n\t\t\t\tdate\n\t\t\t\tpayment\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetScheduledPaymentsInPaymentSchedule($getScheduledPaymentsInput: GetScheduledPaymentsInput!, $getActualPaymentsInput: GetActualPaymentsInput!) {\n\t\tgetScheduledPayments(input: $getScheduledPaymentsInput) {\n\t\t\tscheduled_payments {\n\t\t\t\tid\n\t\t\t\tdate\n\t\t\t\tpayment\n\t\t\t\tscheduled_payment_type\n\t\t\t}\n\t\t}\n\t\tgetActualPayments(input: $getActualPaymentsInput) {\n\t\t\tactual_payments {\n\t\t\t\tid\n\t\t\t\tdate\n\t\t\t\tpayment\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetObjectsInNewAgencyContract {\n\t\tgetObjects {\n      id\n      name\n\t\t}\n\t}\n"): (typeof documents)["\n  query GetObjectsInNewAgencyContract {\n\t\tgetObjects {\n      id\n      name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetAgencyContractInRealEstateAgencyContract($input: GetAgencyContractInput!) {\n\t\tgetAgencyContract(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tagency_contract_signatory {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\ttitle\n\t\t\t\tbased_on\n\t\t\t}\n\t\t\treal_estate_agency_contract_properties {\n\t\t\t\tagency_contract_commission {\n\t\t\t\t\tpercent\n\t\t\t\t\tthreshold\n\t\t\t\t\tmax_days\n\t\t\t\t}\n\t\t\t}\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tresponsible_user {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetAgencyContractInRealEstateAgencyContract($input: GetAgencyContractInput!) {\n\t\tgetAgencyContract(input: $input) {\n\t\t\tagency_contract_properties {\n\t\t\t\tid\n\t\t\t\tnumber\n\t\t\t\tdate\n\t\t\t\tagency_contract_type\n\t\t\t}\n\t\t\tagency_contract_signatory {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\temail\n\t\t\t\tphone\n\t\t\t\ttitle\n\t\t\t\tbased_on\n\t\t\t}\n\t\t\treal_estate_agency_contract_properties {\n\t\t\t\tagency_contract_commission {\n\t\t\t\t\tpercent\n\t\t\t\t\tthreshold\n\t\t\t\t\tmax_days\n\t\t\t\t}\n\t\t\t}\n\t\t\tentity {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tobject {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tagency {\n\t\t\t\tid\n\t\t\t\tname\n\t\t\t}\n\t\t\tresponsible_user {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateAgencyContractInNewAgencyContract($input: CreateAgencyContractInput!) {\n\t\tcreateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n  mutation CreateAgencyContractInNewAgencyContract($input: CreateAgencyContractInput!) {\n\t\tcreateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateAgencyContractInNewAgencyContract($input: UpdateAgencyContractInput!) {\n\t\tupdateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n  mutation UpdateAgencyContractInNewAgencyContract($input: UpdateAgencyContractInput!) {\n\t\tupdateAgencyContract(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetRealEstateAgentInRealEstateAgent($input: GetRealEstateAgentInput!) {\n\t\tgetRealEstateAgent(input: $input) {\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tphone\n\t\t\t}\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tcommon_db_contractors_id\n\t\t\t\tname\n\t\t\t\tinn\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetRealEstateAgentInRealEstateAgent($input: GetRealEstateAgentInput!) {\n\t\tgetRealEstateAgent(input: $input) {\n\t\t\treal_estate_agent {\n\t\t\t\tid\n\t\t\t\tfull_name\n\t\t\t\tphone\n\t\t\t}\n\t\t\tagencies {\n\t\t\t\tid\n\t\t\t\tcommon_db_contractors_id\n\t\t\t\tname\n\t\t\t\tinn\n\t\t\t}\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation CreateRealEstateAgentInNewRealEstateAgent($input: CreateRealEstateAgentInput!) {\n\t\tcreateRealEstateAgent(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation CreateRealEstateAgentInNewRealEstateAgent($input: CreateRealEstateAgentInput!) {\n\t\tcreateRealEstateAgent(input: $input) {\n\t\t\tid\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tmutation UpdateRealEstateAgentInRealEstateAgent($input: UpdateRealEstateAgentInput!) {\n\t\tupdateRealEstateAgent(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t}\n\t}\n"): (typeof documents)["\n\tmutation UpdateRealEstateAgentInRealEstateAgent($input: UpdateRealEstateAgentInput!) {\n\t\tupdateRealEstateAgent(input: $input) {\n\t\t\tid\n\t\t\tfull_name\n\t\t}\n\t}\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n\tquery GetRealEstateAgentsInRealEstateAgents($input: GetRealEstateAgentsInput!) {\n\t\tgetRealEstateAgents(input: $input) {\n\t\t\treal_estate_agents {\n\t\t\t\treal_estate_agent {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tphone\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetRealEstateAgentsInRealEstateAgents($input: GetRealEstateAgentsInput!) {\n\t\tgetRealEstateAgents(input: $input) {\n\t\t\treal_estate_agents {\n\t\t\t\treal_estate_agent {\n\t\t\t\t\tid\n\t\t\t\t\tfull_name\n\t\t\t\t\tphone\n\t\t\t\t}\n\t\t\t}\n\t\t\ttotal_count\n\t\t}\n\t}\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;